imports:
  - { resource: config.yml }

doctrine:
  dbal:
    dbname: supla_test

framework:
  profiler:
    collect: false
  session:
    storage_id: session.storage.mock_file
  test: ~

security:
  firewalls:
    main:
      http_basic: ~

services:
  SuplaBundle\Supla\SuplaServer: '@SuplaBundle\Supla\SuplaServerMock'
  SuplaBundle\Supla\SuplaServerMockCommandsCollector:
    public: false
    tags: [{name: data_collector, template: '@Supla/Supla/supla-server-mock-data-collector.html.twig', id: 'supla.supla_server_mock_data_collector'}]

swiftmailer:
  disable_delivery: true

web_profiler:
  toolbar: false
  intercept_redirects: false
